# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UuAj8gl1phgr9mDYTwFDsEBmVQ-frSRC
"""

probitoftwoEvents=float(input("the probability of A intersection B:"))
probitofA=3/6
probitofBandA=probitoftwoEvents/probitofA
print("Probabaility of B and A is:",probitofBandA)