# -*- coding: utf-8 -*-
"""exp4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eKIOMNvyg3bWb2cHnGhsgVT3cLyxp44W
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from copy import deepcopy
data=pd.read_csv('/content/sample_data/data2.csv')
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   f1=data['A'].values
f2=data['B'].values
X=np.array(list(zip(f1,f2)))
plt.scatter(f1,f2,c='black',s=200)
def dist(a,b,ax=1):
  return np.linalg.norm(a-b,axis=ax)
k=3
C=data.values[0:k]
C_x=C[0][0],C[1][0],C[2][0]
C_y=C[0][1],C[1][1],C[2][1]
print("Data points with initial centroids")
plt.scatter(f1,f2,c="#050505",s=200)
plt.scatter(C_x,C_y,marker='*',s=200,c='pink')
C_old=np.zeros(C.shape)
clusters=np.zeros(len(X))
error=dist(C,C_old,None)
while error!=0:
  for i in range(len(X)):
    distances=dist(X[i],C)
    cluster=np.argmin(distances)
    clusters[i]=cluster
  C_old=deepcopy(C)
  for i in range(k):
    points=[X[j]for j in range(len(X))if clusters[j]==i]
    C[i]=np.mean(points,axis=0)
  error=dist(C,C_old,None)
print("Coloured data points in clusters with cluster centroids(*)")
colors=['r','g','b']
fig,ax=plt.subplots()
for i in range(k):
  points=np.array([X[j]for j in range(len(X))if clusters[j]==i])
  ax.scatter(points[:,0],points[:,1],s=200,c=colors[i])
ax.scatter(C[:,0],C[:,1],marker='*',s=200,c='#050505')
dist([0.906,0.606],C)
cluster=np.argmin(distances)
print("Data point[0.0906,0.606]belongs to cluster",cluster)



