# -*- coding: utf-8 -*-
"""exp5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PV53U5cPvxHCQvmKK7kLMu4fBzmKwRCL
"""

import numpy as np
import pandas as pd
loanrisk=pd.read_csv('/content/sample_data/Expt5 (2).csv')
display(loanrisk)
ct1=pd.crosstab(loanrisk['recreation'],loanrisk['Class'],margins=True)
ct2=pd.crosstab(loanrisk['status'],loanrisk['Class'],margins=True)
print("\nPart A:")
print("The unconditional probability of 'golf'",ct1.iloc[2,0]/ct1.iloc[5,0])
print("the conditional probability of single given medRisk %.3f"%(ct2.iloc[1,2]/ct2.iloc[2,2]))
print("\nPart B:")
print("some more results using bayes theorem: Posterior probability=(Prior*Likelihood)/Evidence")
Prior=ct2.iloc[2,2]/ct2.iloc[2,2]
Likelihood=ct2.iloc[1,2]/ct2.iloc[2,2]

Evidence=ct2.iloc[1,3]/ct2.iloc[2,3]
print("probability of medRisk given single using bayes theorem %.3f"%(Prior*Likelihood/Evidence))
ct1=pd.crosstab(loanrisk['income'],loanrisk['Class'],margins=True)
ct2=pd.crosstab(loanrisk['recreation'],loanrisk['Class'],margins=True)
ct3=pd.crosstab(loanrisk['job'],loanrisk['Class'],margins=True)
ct4=pd.crosstab(loanrisk['status'],loanrisk['Class'],margins=True)
ct5=pd.crosstab(loanrisk['age-group'],loanrisk['Class'],margins=True)
ct6=pd.crosstab(loanrisk['home-owner'],loanrisk['Class'],margins=True)
p_mediumgnlowRisk=ct1.iloc[2,1]/ct1.iloc[3,1]
p_golfgnlowRisk=ct2.iloc[2,1]/ct2.iloc[5,1]
p_bankinggnlowRisk=ct3.iloc[0,1]/ct3.iloc[7,1]
p_marriedgnlowRisk=ct4.iloc[0,1]/ct4.iloc[2,1]
p_fortiesgnlowRisk=ct5.iloc[1,1]/ct5.iloc[4,1]
p_yesgnlowRisk=ct6.iloc[1,1]/ct6.iloc[2,1]
p_x_lowRisk=p_mediumgnlowRisk*p_golfgnlowRisk*p_bankinggnlowRisk*p_marriedgnlowRisk*p_fortiesgnlowRisk*p_yesgnlowRisk
print("the likelihood of the predictors(medium,golf,banking,married,forties,yes)for Class lowRisk",'%.3f'%p_x_lowRisk)
lowRisk=ct6.iloc[2,1]/ct6.iloc[2,3]
print("The prorir probability of Class lowRisk is",'%.3f'%lowRisk)
lowRisk_x = p_x_lowRisk*lowRisk
print('The posterior probability of lowRisk given the predictors(medium,golf,banking,married,forties,yes) is', '%.3f'%lowRisk_x)